name: Bandit Scan

on: [push] 

jobs:
  bandit-scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Bandit Scan
        uses: Hacash/bandit-scan@v2
        with:
          path: '.'